# Generated by Django 4.1.2 on 2022-10-24 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата события')),
                ('views', models.IntegerField(blank=True, verbose_name='Количество показов')),
                ('clicks', models.IntegerField(blank=True, verbose_name='Количество кликов')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
            ],
        ),
    ]
