# Generated by Django 4.1.2 on 2022-10-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='event_date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата события'),
        ),
    ]
